### Step 1: Extract Data

In [1]:
import pandas as pd

In [2]:
import os

In [3]:
import pandas as pd
import os

# Define folder path
path = "/Users/sabatehrani/Desktop/Historical_Weather_Data/archive (3)/NOAA Weather cities 2015-2020/"


def extract_data(path):

    files = [
        "Weather all cities 2015.csv",
        "Weather all cities 2016.csv",
        "Weather all cities 2017.csv",
        "Weather all cities 2018.csv",
        "Weather all cities 2019.csv",
        "Weather all cities 2020.csv"
    ]


    # Step 1: Check if files exist
    for file in files:

        if not os.path.exists(path + file):
            print(file + " does not exist")
            continue

        else:
            print(file + " exists")


    # Step 2: Read CSV files and check if they are empty
    has_empty_file = False

    df_2015 = pd.read_csv(path + "Weather all cities 2015.csv")
    if df_2015.empty:
        print("df_2015 is empty")
        has_empty_file = True

    df_2016 = pd.read_csv(path + "Weather all cities 2016.csv")
    if df_2016.empty:
        print("df_2016 is empty")
        has_empty_file = True

    df_2017 = pd.read_csv(path + "Weather all cities 2017.csv")
    if df_2017.empty:
        print("df_2017 is empty")
        has_empty_file = True

    df_2018 = pd.read_csv(path + "Weather all cities 2018.csv")
    if df_2018.empty:
        print("df_2018 is empty")
        has_empty_file = True

    df_2019 = pd.read_csv(path + "Weather all cities 2019.csv")
    if df_2019.empty:
        print("df_2019 is empty")
        has_empty_file = True

    df_2020 = pd.read_csv(path + "Weather all cities 2020.csv")
    if df_2020.empty:
        print("df_2020 is empty")
        has_empty_file = True


    # Step 3: Report if one or more files are empty
    if has_empty_file == True:
        print("One or more files are empty")


    # Step 4: Combine non-empty files
    valid_dataframes = [
        df for df in
        [df_2015, df_2016, df_2017, df_2018, df_2019, df_2020]
        if not df.empty
    ]

    df = pd.concat(
        valid_dataframes,
        ignore_index=True
    )


    # Step 5: Check required columns
    has_required_columns = True

    if "Date" not in df.columns:
        print("Date column is missing")
        has_required_columns = False

    if "ID" not in df.columns:
        print("ID column is missing")
        has_required_columns = False


    # Step 6: Return extracted data
    if has_required_columns == True:
        return df

In [4]:
df = extract_data(path)

Weather all cities 2015.csv exists
Weather all cities 2016.csv exists
Weather all cities 2017.csv exists
Weather all cities 2018.csv exists
Weather all cities 2019.csv exists
Weather all cities 2020.csv exists

In [5]:
df.head()

,Unnamed: 0,Date,ID,AWND,DAPR,DATN,DATX,DWPR,EVAP,MDPR,...,WT09,WT10,WT11,DASF,MDSF,THIC,WT13,WT14,WT16,WT18
0,0,20150101,AE000041196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,20150101,AEM00041194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,20150101,AEM00041217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,20150101,AFM00040938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,20150101,AFM00040948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.tail()

,Unnamed: 0,Date,ID,AWND,DAPR,DATN,DATX,DWPR,EVAP,MDPR,...,WT09,WT10,WT11,DASF,MDSF,THIC,WT13,WT14,WT16,WT18
11379742,1536308,20201103,USR0000NSAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11379743,1536309,20201103,USR0000PLGV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11379744,1536310,20201103,USR0000WBRF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11379745,1536311,20201103,USW00013701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11379746,1536312,20201103,USW00013867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11379747 entries, 0 to 11379746
Data columns (total 71 columns):
 #   Column      Dtype
---  ------      -----
 0   Unnamed: 0  int64
 1   Date        int64
 2   ID          object
 3   AWND        float64
 4   DAPR        float64
 5   DATN        float64
 6   DATX        float64
 7   DWPR        float64
 8   EVAP        float64
 9   MDPR        float64
 10  MDTN        float64
 11  MDTX        float64
 12  MNPN        float64
 13  MXPN        float64
 14  PGTM        float64
 15  PRCP        float64
 16  PSUN        float64
 17  SN31        float64
 18  SN32        float64
 19  SN33        float64
 20  SN35        float64
 21  SN36        float64
 22  SN51        float64
 23  SN52        float64
 24  SN53        float64
 25  SN55        float64
 26  SN56        float64
 27  SNOW        float64
 28  SNWD        float64
 29  SX31        float64
 30  SX32        float64
 31  SX33        float64
 32  SX35        float64
 33  SX36        float64
 34  SX51        float64
 35  SX52        float64
 36  SX53        float64
 37  SX55        float64
 38  SX56        float64
 39  TAVG        float64
 40  TMAX        float64
 41  TMIN        float64
 42  TOBS        float64
 43  TSUN        float64
 44  WDF2        float64
 45  WDF5        float64
 46  WDFG        float64
 47  WDMV        float64
 48  WESD        float64
 49  WESF        float64
 50  WSF2        float64
 51  WSF5        float64
 52  WSFG        float64
 53  WT01        float64
 54  WT02        float64
 55  WT03        float64
 56  WT04        float64
 57  WT05        float64
 58  WT06        float64
 59  WT07        float64
 60  WT08        float64
 61  WT09        float64
 62  WT10        float64
 63  WT11        float64
 64  DASF        float64
 65  MDSF        float64
 66  THIC        float64
 67  WT13        float64
 68  WT14        float64
 69  WT16        float64
 70  WT18        float64
dtypes: float64(68), int64(2), object(1)
memory usage: 6.0+ GB

In [8]:
df.dtypes

Unnamed: 0      int64
Date            int64
ID             object
AWND          float64
DAPR          float64
               ...
THIC          float64
WT13          float64
WT14          float64
WT16          float64
WT18          float64
Length: 71, dtype: object

In [9]:
df.columns

Index(['Unnamed: 0', 'Date', 'ID', 'AWND', 'DAPR', 'DATN', 'DATX', 'DWPR',
       'EVAP', 'MDPR', 'MDTN', 'MDTX', 'MNPN', 'MXPN', 'PGTM', 'PRCP', 'PSUN',
       'SN31', 'SN32', 'SN33', 'SN35', 'SN36', 'SN51', 'SN52', 'SN53', 'SN55',
       'SN56', 'SNOW', 'SNWD', 'SX31', 'SX32', 'SX33', 'SX35', 'SX36', 'SX51',
       'SX52', 'SX53', 'SX55', 'SX56', 'TAVG', 'TMAX', 'TMIN', 'TOBS', 'TSUN',
       'WDF2', 'WDF5', 'WDFG', 'WDMV', 'WESD', 'WESF', 'WSF2', 'WSF5', 'WSFG',
       'WT01', 'WT02', 'WT03', 'WT04', 'WT05', 'WT06', 'WT07', 'WT08', 'WT09',
       'WT10', 'WT11', 'DASF', 'MDSF', 'THIC', 'WT13', 'WT14', 'WT16', 'WT18'],
      dtype='object')

In [10]:
df.shape

(11379747, 71)

In [11]:
df.isnull().sum()

Unnamed: 0           0
Date                 0
ID                   0
AWND          11039415
DAPR          11308552
                ...
THIC          11379727
WT13          11379746
WT14          11379718
WT16          11379694
WT18          11379739
Length: 71, dtype: int64

In [12]:
df.isnull()

,Unnamed: 0,Date,ID,AWND,DAPR,DATN,DATX,DWPR,EVAP,MDPR,...,WT09,WT10,WT11,DASF,MDSF,THIC,WT13,WT14,WT16,WT18
0,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11379742,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
11379743,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
11379744,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
11379745,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
11379746,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [13]:
df.duplicated()

0           False
1           False
2           False
3           False
4           False
            ...
11379742    False
11379743    False
11379744    False
11379745    False
11379746    False
Length: 11379747, dtype: bool

In [14]:
df.duplicated().sum()

0

### Step 2: Clean Data

In [15]:
def clean_data(df):

    # Make a copy
    df = df.copy()

    # Check duplicates before removing
    print("Duplicated before:", df.duplicated().sum())

    # Remove duplicates
    df = df.drop_duplicates()

    # Check duplicates after removing
    print("Duplicated after:", df.duplicated().sum())

    # Check missing values before removing
    print("Missing values before:")
    print(df.isnull().sum())

    # Remove null values from important columns
    df = df.dropna(subset=["Date", "ID"])

    # Check missing values after removing
    print("Missing values after:")
    print(df.isnull().sum())

    return df

In [16]:
clean_df = clean_data(df)

Duplicated before: 0
Duplicated after: 0
Missing values before:
Unnamed: 0           0
Date                 0
ID                   0
AWND          11039415
DAPR          11308552
                ...
THIC          11379727
WT13          11379746
WT14          11379718
WT16          11379694
WT18          11379739
Length: 71, dtype: int64
Missing values after:
Unnamed: 0           0
Date                 0
ID                   0
AWND          11039415
DAPR          11308552
                ...
THIC          11379727
WT13          11379746
WT14          11379718
WT16          11379694
WT18          11379739
Length: 71, dtype: int64

In [17]:
clean_df.head()

,Unnamed: 0,Date,ID,AWND,DAPR,DATN,DATX,DWPR,EVAP,MDPR,...,WT09,WT10,WT11,DASF,MDSF,THIC,WT13,WT14,WT16,WT18
0,0,20150101,AE000041196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,20150101,AEM00041194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,20150101,AEM00041217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,20150101,AFM00040938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,20150101,AFM00040948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
clean_df.tail()

,Unnamed: 0,Date,ID,AWND,DAPR,DATN,DATX,DWPR,EVAP,MDPR,...,WT09,WT10,WT11,DASF,MDSF,THIC,WT13,WT14,WT16,WT18
11379742,1536308,20201103,USR0000NSAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11379743,1536309,20201103,USR0000PLGV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11379744,1536310,20201103,USR0000WBRF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11379745,1536311,20201103,USW00013701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11379746,1536312,20201103,USW00013867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
clean_df.shape

(11379747, 71)

In [20]:
clean_df.dtypes

Unnamed: 0      int64
Date            int64
ID             object
AWND          float64
DAPR          float64
               ...
THIC          float64
WT13          float64
WT14          float64
WT16          float64
WT18          float64
Length: 71, dtype: object

In [21]:
clean_df.duplicated().sum()

0

### It is obvious

In [22]:
clean_df.duplicated(subset=["Date", "ID"]).sum()

0

In [23]:
clean_df.isnull().sum()

Unnamed: 0           0
Date                 0
ID                   0
AWND          11039415
DAPR          11308552
                ...
THIC          11379727
WT13          11379746
WT14          11379718
WT16          11379694
WT18          11379739
Length: 71, dtype: int64

In [24]:
clean_df[["Date", "ID"]].isnull().sum()

Date    0
ID      0
dtype: int64

### Step 3: Transform and Standardize Data

In [24]:
def transform_data(clean_df):

    # Make a copy
    transformed_df = clean_df.copy()

    # Standardize Date
    transformed_df["Date"] = pd.to_datetime(
        transformed_df["Date"],
        format="%Y%m%d",
        errors="coerce"
    )

    # Standardize Temperature
    transformed_df["TAVG"] = transformed_df["TAVG"] / 10
    transformed_df["TMAX"] = transformed_df["TMAX"] / 10
    transformed_df["TMIN"] = transformed_df["TMIN"] / 10

    return transformed_df

In [25]:
transformed_df = transform_data(clean_df)

In [26]:
transformed_df [["Date", "ID", "TAVG", "TMAX", "TMIN"]].head()

        Date           ID  TAVG  TMAX  TMIN
0 2015-01-01  AE000041196  20.6   NaN   NaN
1 2015-01-01  AEM00041194  22.5  28.6  18.0
2 2015-01-01  AEM00041217  21.1  28.2  14.6
3 2015-01-01  AFM00040938   8.7   NaN   NaN
4 2015-01-01  AFM00040948   1.9   NaN   NaN

In [27]:
transformed_df [["Date", "ID", "TAVG", "TMAX", "TMIN"]].tail()

               Date           ID  TAVG  TMAX  TMIN
11379742 2020-11-03  USR0000NSAR   2.1   5.0  -1.7
11379743 2020-11-03  USR0000PLGV  16.4  25.0  11.1
11379744 2020-11-03  USR0000WBRF   9.8  23.9  -3.3
11379745 2020-11-03  USW00013701   NaN   8.3   3.9
11379746 2020-11-03  USW00013867   NaN   9.4   1.7

In [28]:
transformed_df [["Date", "ID", "TAVG", "TMAX", "TMIN"]].dtypes

Date    datetime64[ns]
ID              object
TAVG           float64
TMAX           float64
TMIN           float64
dtype: object

In [29]:
transformed_df["Date"].isnull().sum()

0

In [30]:
transformed_df.head()

,Unnamed: 0,Date,ID,AWND,DAPR,DATN,DATX,DWPR,EVAP,MDPR,...,WT09,WT10,WT11,DASF,MDSF,THIC,WT13,WT14,WT16,WT18
0,0,2015-01-01,AE000041196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2015-01-01,AEM00041194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2015-01-01,AEM00041217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2015-01-01,AFM00040938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2015-01-01,AFM00040948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
transformed_df.tail()

,Unnamed: 0,Date,ID,AWND,DAPR,DATN,DATX,DWPR,EVAP,MDPR,...,WT09,WT10,WT11,DASF,MDSF,THIC,WT13,WT14,WT16,WT18
11379742,1536308,2020-11-03,USR0000NSAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11379743,1536309,2020-11-03,USR0000PLGV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11379744,1536310,2020-11-03,USR0000WBRF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11379745,1536311,2020-11-03,USW00013701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11379746,1536312,2020-11-03,USW00013867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 4: Data Quality Checks

In [31]:
def check_data_quality(transformed_df):

    # Check for duplicate rows
    duplicate_count = transformed_df.duplicated().sum()

    # Check for missing values in important columns
    missing_values = transformed_df[["Date", "ID"]].isnull().sum().sum()

    # Stop pipeline if data quality check fails
    if duplicate_count > 0 or missing_values > 0:
        raise ValueError("Data quality check failed")
    else:
        print("Data quality check passed!")

In [32]:
check_data_quality(transformed_df)

Data quality check passed!

### Step 5: Load Data

In [14]:
from sqlalchemy import create_engine

In [15]:
def load_data(transformed_df):

    # Create connection to PostgreSQL
    engine = create_engine(
    "postgresql+psycopg2://postgres:sabatehrani22647741@localhost:5432/weather_etl_db"
)
    # Load data into PostgreSQL
    transformed_df.to_sql(
    "weather_data",
    engine,
    if_exists = "replace",
    index = False,
    chunksize = 10000
    )

    print("Data loaded successfully!")

In [16]:
load_data(transformed_df.head(10))

Data loaded successfully!

In [17]:
transformed_df.columns

Index(['Unnamed: 0', 'Date', 'ID', 'AWND', 'DAPR', 'DATN', 'DATX', 'DWPR',
       'EVAP', 'MDPR', 'MDTN', 'MDTX', 'MNPN', 'MXPN', 'PGTM', 'PRCP', 'PSUN',
       'SN31', 'SN32', 'SN33', 'SN35', 'SN36', 'SN51', 'SN52', 'SN53', 'SN55',
       'SN56', 'SNOW', 'SNWD', 'SX31', 'SX32', 'SX33', 'SX35', 'SX36', 'SX51',
       'SX52', 'SX53', 'SX55', 'SX56', 'TAVG', 'TMAX', 'TMIN', 'TOBS', 'TSUN',
       'WDF2', 'WDF5', 'WDFG', 'WDMV', 'WESD', 'WESF', 'WSF2', 'WSF5', 'WSFG',
       'WT01', 'WT02', 'WT03', 'WT04', 'WT05', 'WT06', 'WT07', 'WT08', 'WT09',
       'WT10', 'WT11', 'DASF', 'MDSF', 'THIC', 'WT13', 'WT14', 'WT16', 'WT18'],
      dtype='object')

In [18]:
load_data(transformed_df.head(20))

Data loaded successfully!

In [19]:
load_data(transformed_df)

Data loaded successfully!

### Step 6: Build Complete ETL Pipeline¶

In [20]:
def run_pipeline(path):

    # Extract
    df = extract_data(path)

    # Clean
    clean_df = clean_data(df)

    # Transform
    transformed_df = transform_data(clean_df)

    # Data Quality
    check_data_quality(transformed_df)

    # Load
    load_data(transformed_df)

    print("ETL pipeline completed successfully!")

In [21]:
run_pipeline(path)

Weather all cities 2015.csv exists
Weather all cities 2016.csv exists
Weather all cities 2017.csv exists
Weather all cities 2018.csv exists
Weather all cities 2019.csv exists
Weather all cities 2020.csv exists
Duplicated before: 0
Duplicated after: 0
Missing values before:
Unnamed: 0           0
Date                 0
ID                   0
AWND          11039415
DAPR          11308552
                ...
THIC          11379727
WT13          11379746
WT14          11379718
WT16          11379694
WT18          11379739
Length: 71, dtype: int64
Missing values after:
Unnamed: 0           0
Date                 0
ID                   0
AWND          11039415
DAPR          11308552
                ...
THIC          11379727
WT13          11379746
WT14          11379718
WT16          11379694
WT18          11379739
Length: 71, dtype: int64
Data quality check passed!
Data loaded successfully!
ETL pipeline completed successfully!

### Step 7: Add Logging and Error Handling

In [22]:
import logging
import os

In [23]:
# Create logs folder
os.makedirs("logs", exist_ok=True)

# Configure logging
logging.basicConfig(
    filename="logs/pipeline.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

In [25]:
def run_pipeline(path):

    try:
        # Start pipeline
        logging.info("ETL pipeline started")

        # Extract
        df = extract_data(path)
        logging.info(f"{len(df)} records extracted successfully")

        # Clean
        clean_df = clean_data(df)
        logging.info(f"{len(clean_df)} records cleaned successfully")

        # Transform
        transformed_df = transform_data(clean_df)
        logging.info(f"{len(transformed_df)} records transformed successfully")

        # Data Quality
        check_data_quality(transformed_df)
        logging.info("Data quality check passed")

        # Load
        load_data(transformed_df)
        logging.info("Data successfully loaded into PostgreSQL")

        # Complete pipeline
        logging.info("ETL pipeline completed successfully!")
        print("ETL pipeline completed successfully!")

    except Exception as e:
        logging.error(f"Pipeline failed: {e}")
        print("Pipeline failed:", e)

In [26]:
run_pipeline(path)

Weather all cities 2015.csv exists
Weather all cities 2016.csv exists
Weather all cities 2017.csv exists
Weather all cities 2018.csv exists
Weather all cities 2019.csv exists
Weather all cities 2020.csv exists
Duplicated before: 0
Duplicated after: 0
Missing values before:
Unnamed: 0           0
Date                 0
ID                   0
AWND          11039415
DAPR          11308552
                ...
THIC          11379727
WT13          11379746
WT14          11379718
WT16          11379694
WT18          11379739
Length: 71, dtype: int64
Missing values after:
Unnamed: 0           0
Date                 0
ID                   0
AWND          11039415
DAPR          11308552
                ...
THIC          11379727
WT13          11379746
WT14          11379718
WT16          11379694
WT18          11379739
Length: 71, dtype: int64
Data quality check passed!
Data loaded successfully!
ETL pipeline completed successfully!